// Generated by tools/build_pwa.mjs. Do not edit by hand.
const CACHE = 'glacial-strikers-ed61fb46d988';
const FILES = [
  "./",
  "./assets/fonts/jersey-10-latin-ext.woff2",
  "./assets/fonts/jersey-10-latin.woff2",
  "./assets/fonts/pixelify-sans-latin-ext.woff2",
  "./assets/fonts/pixelify-sans-latin.woff2",
  "./assets/gfx/atlas.json",
  "./assets/gfx/away_0.webp",
  "./assets/gfx/home_0.webp",
  "./assets/gfx/rink_backdrop.webp",
  "./assets/icons/apple-touch-icon.png",
  "./assets/icons/favicon-32.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/icons/maskable-512.png",
  "./index.html",
  "./manifest.webmanifest",
  "./src/abilities.js",
  "./src/achievements.js",
  "./src/ai.js",
  "./src/assets.js",
  "./src/audio.js",
  "./src/clips.js",
  "./src/commentary.js",
  "./src/data.js",
  "./src/drills.js",
  "./src/entities.js",
  "./src/fonts.css",
  "./src/fx.js",
  "./src/hud.js",
  "./src/input.js",
  "./src/league.js",
  "./src/lockerroom.js",
  "./src/main.js",
  "./src/match.js",
  "./src/net.js",
  "./src/progress.js",
  "./src/render.js",
  "./src/replay.js",
  "./src/rink.js",
  "./src/rivals.js",
  "./src/styles.css",
  "./src/ui.js",
  "./src/util.js"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith('glacial-strikers-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Cache first, so the game starts instantly and works with no connection.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
    return res;
  }).catch(() => (req.mode === 'navigate' ? caches.match('./index.html') : undefined))));
});
