// Generated by tools/build_pwa.mjs. Do not edit by hand.
const CACHE = 'glacial-strikers-c10923a776cd';
const FILES = [
  "./",
  "./assets/fonts/jersey-10-latin-ext.woff2",
  "./assets/fonts/jersey-10-latin.woff2",
  "./assets/fonts/pixelify-sans-latin-ext.woff2",
  "./assets/fonts/pixelify-sans-latin.woff2",
  "./assets/gfx/arena_aurora_palace.webp",
  "./assets/gfx/arena_ember_dome.webp",
  "./assets/gfx/arena_pine_pond.webp",
  "./assets/gfx/atlas.json",
  "./assets/gfx/away_0.webp",
  "./assets/gfx/cutins/aurora_royals_c.webp",
  "./assets/gfx/cutins/aurora_royals_d.webp",
  "./assets/gfx/cutins/aurora_royals_g.webp",
  "./assets/gfx/cutins/aurora_royals_w.webp",
  "./assets/gfx/cutins/bram.webp",
  "./assets/gfx/cutins/ember_comets_c.webp",
  "./assets/gfx/cutins/ember_comets_d.webp",
  "./assets/gfx/cutins/ember_comets_g.webp",
  "./assets/gfx/cutins/ember_comets_w.webp",
  "./assets/gfx/cutins/gilded_rams_c.webp",
  "./assets/gfx/cutins/gilded_rams_d.webp",
  "./assets/gfx/cutins/gilded_rams_g.webp",
  "./assets/gfx/cutins/gilded_rams_w.webp",
  "./assets/gfx/cutins/halla.webp",
  "./assets/gfx/cutins/nix.webp",
  "./assets/gfx/cutins/obsidian_ravens_c.webp",
  "./assets/gfx/cutins/obsidian_ravens_d.webp",
  "./assets/gfx/cutins/obsidian_ravens_g.webp",
  "./assets/gfx/cutins/obsidian_ravens_w.webp",
  "./assets/gfx/cutins/pinewood_lynx_c.webp",
  "./assets/gfx/cutins/pinewood_lynx_d.webp",
  "./assets/gfx/cutins/pinewood_lynx_g.webp",
  "./assets/gfx/cutins/pinewood_lynx_w.webp",
  "./assets/gfx/cutins/volta.webp",
  "./assets/gfx/home_0.webp",
  "./assets/gfx/home_1.webp",
  "./assets/gfx/locker_room.webp",
  "./assets/gfx/near_glass.webp",
  "./assets/gfx/rink_backdrop.webp",
  "./assets/gfx/rival_aurora_royals_0.webp",
  "./assets/gfx/rival_ember_comets_0.webp",
  "./assets/gfx/rival_gilded_rams_0.webp",
  "./assets/gfx/rival_obsidian_ravens_0.webp",
  "./assets/gfx/rival_pinewood_lynx_0.webp",
  "./assets/icons/apple-touch-icon.png",
  "./assets/icons/favicon-32.png",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/icons/maskable-512.png",
  "./index.html",
  "./manifest.webmanifest",
  "./src/abilities.js",
  "./src/achievements.js",
  "./src/ai.js",
  "./src/assets.js",
  "./src/audio.js",
  "./src/awards.js",
  "./src/clips.js",
  "./src/commentary.js",
  "./src/daily.js",
  "./src/data.js",
  "./src/drills.js",
  "./src/entities.js",
  "./src/fonts.css",
  "./src/fx.js",
  "./src/hud.js",
  "./src/input.js",
  "./src/league.js",
  "./src/lockerroom.js",
  "./src/main.js",
  "./src/match.js",
  "./src/music.js",
  "./src/net.js",
  "./src/progress.js",
  "./src/render.js",
  "./src/replay.js",
  "./src/rink.js",
  "./src/rivals.js",
  "./src/songs.js",
  "./src/styles.css",
  "./src/ui.js",
  "./src/util.js"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith('glacial-strikers-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Cache first, so the game starts instantly and works with no connection.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
    return res;
  }).catch(() => (req.mode === 'navigate' ? caches.match('./index.html') : undefined))));
});
