// Writes sw.js: a service worker that precaches every file the game needs, so an
// installed copy plays offline. Re-run after changing any game file:
//   node tools/build_pwa.mjs
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, relative } from 'node:path';

const root = new URL('..', import.meta.url).pathname;
const include = ['index.html', 'manifest.webmanifest', 'src', 'assets/gfx', 'assets/fonts', 'assets/icons'];
const files = [];
const walk = (p) => {
  const full = join(root, p);
  if (statSync(full).isDirectory()) for (const f of readdirSync(full)) walk(join(p, f));
  else if (!/\.DS_Store$/.test(p)) files.push(p);
};
include.forEach(walk);
files.sort();
const hash = createHash('sha256');
for (const f of files) hash.update(f).update(readFileSync(join(root, f)));
const version = hash.digest('hex').slice(0, 12);
const list = ['./', ...files.map((f) => './' + relative('.', f))];

writeFileSync(join(root, 'sw.js'), `// Generated by tools/build_pwa.mjs. Do not edit by hand.
const CACHE = 'glacial-strikers-${version}';
const FILES = ${JSON.stringify(list, null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k.startsWith('glacial-strikers-') && k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});

// Cache first, so the game starts instantly and works with no connection.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
    return res;
  }).catch(() => (req.mode === 'navigate' ? caches.match('./index.html') : undefined))));
});
`);
console.log(`sw.js: ${list.length} files, cache ${version}`);
